#server.port=8080
#spring.application.name=money
#spring.security.user.password=test
#debug=false
#spring.data.mongodb.uri=mongodb+srv://sauravjaiswal999:VabU3UDyodADOPDQ@fyndcare.1aoul.mongodb.net/?retryWrites=true&w=majority&appName=FyndCare
#spring.data.mongodb.database=budget
#spring.data.mongodb.auto-index-creation=true
#spring.main.log-startup-info=false
#spring.main.allow-circular-references=true
#spring.mvc.cors.allowed-origins=http://localhost:3000
#spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
#spring.mvc.cors.allowed-headers=*
#spring.mvc.cors.allow-credentials=true

